### ISSUE TITLE
[Feature] Dataset name input validation

### ISSUE THREAD

**Issue by jcace** [jimmylee/delta-nextjs-client#7]
Dataset name (when adding a new Dataset) - Needs to be lowercase letters/numbers and hyphens only (and no consecutive hyphens). Less than 255 chars in length. 

Frontend - In terms of the UX - would be awesome if it like auto-lowercased everything as you typed and replaced spaces with “-” + ignored invalid input

**Comment by jimmylee** [comment]
@elijaharita use the method here https://github.com/application-research/delta-nextjs-client/blob/master/common/utilities.ts#L69 and or modify it, this `slug` method is URL approved and therefore can be used in this case with slight modification.
